using System.Collections.Generic;

namespace _591RentPractice
{
    public static class RentalListingData
    {
        public static List<RentalListing> GetData() => new List<RentalListing>
    {
        new RentalListing
        {
            LocationCity     = "高雄市",
            LocationDistrict = "苓雅區",
            Type             = "整層住家",
            Rent             = 35500,
            Rooms            = 3,
            Bathrooms        = 1,
            IsNearMRT        = true,
            IsNewlyListed    = true,
            AllowsPets       = true,
            ShortTermRent    = false,
            BuildingType     = "公寓",
            SizePing         = 31.0,
            Floor            = 4,
            TotalFloors      = 6,
            HasAC            = true,
            HasWasher        = false,
            HasFridge        = false,
            HasWaterHeater   = true,
            HasGas           = true,
            HasInternet      = true,
            HasBed           = false,
            HasParking       = false,
            HasElevator      = false,
            HasBalcony       = true,
        },
        new RentalListing
        {
            LocationCity     = "桃園市",
            LocationDistrict = "桃園區",
            Type             = "獨立套房",
            Rent             = 19000,
            Rooms            = 1,
            Bathrooms        = 1,
            IsNearMRT        = false,
            IsNewlyListed    = false,
            AllowsPets       = false,
            ShortTermRent    = false,
            BuildingType     = "公寓",
            SizePing         = 12.0,
            Floor            = 3,
            TotalFloors      = 5,
            HasAC            = false,
            HasWasher        = true,
            HasFridge        = true,
            HasWaterHeater   = true,
            HasGas           = false,
            HasInternet      = false,
            HasBed           = false,
            HasParking       = false,
            HasElevator      = true,
            HasBalcony       = true,
        },
        new RentalListing
        {
            LocationCity     = "桃園市",
            LocationDistrict = "楊梅區",
            Type             = "獨立套房",
            Rent             = 8500,
            Rooms            = 1,
            Bathrooms        = 1,
            IsNearMRT        = true,
            IsNewlyListed    = false,
            AllowsPets       = false,
            ShortTermRent    = false,
            BuildingType     = "公寓",
            SizePing         = 12.6,
            Floor            = 3,
            TotalFloors      = 5,
            HasAC            = true,
            HasWasher        = true,
            HasFridge        = false,
            HasWaterHeater   = true,
            HasGas           = true,
            HasInternet      = false,
            HasBed           = false,
            HasParking       = false,
            HasElevator      = false,
            HasBalcony       = false,
        },
        new RentalListing
        {
            LocationCity     = "台北市",
            LocationDistrict = "文山區",
            Type             = "整層住家",
            Rent             = 38000,
            Rooms            = 2,
            Bathrooms        = 2,
            IsNearMRT        = false,
            IsNewlyListed    = false,
            AllowsPets       = false,
            ShortTermRent    = true,
            BuildingType     = "透天厝",
            SizePing         = 38.1,
            Floor            = 3,
            TotalFloors      = 3,
            HasAC            = true,
            HasWasher        = false,
            HasFridge        = true,
            HasWaterHeater   = true,
            HasGas           = true,
            HasInternet      = true,
            HasBed           = true,
            HasParking       = false,
            HasElevator      = false,
            HasBalcony       = true,
        },
        new RentalListing
        {
            LocationCity     = "台北市",
            LocationDistrict = "內湖區",
            Type             = "獨立套房",
            Rent             = 17000,
            Rooms            = 1,
            Bathrooms        = 1,
            IsNearMRT        = false,
            IsNewlyListed    = false,
            AllowsPets       = false,
            ShortTermRent    = false,
            BuildingType     = "電梯大樓",
            SizePing         = 9.9,
            Floor            = 10,
            TotalFloors      = 14,
            HasAC            = true,
            HasWasher        = false,
            HasFridge        = false,
            HasWaterHeater   = true,
            HasGas           = true,
            HasInternet      = true,
            HasBed           = true,
            HasParking       = false,
            HasElevator      = true,
            HasBalcony       = true,
        },
        new RentalListing
        {
            LocationCity     = "高雄市",
            LocationDistrict = "鼓山區",
            Type             = "獨立套房",
            Rent             = 15000,
            Rooms            = 1,
            Bathrooms        = 1,
            IsNearMRT        = false,
            IsNewlyListed    = false,
            AllowsPets       = false,
            ShortTermRent    = true,
            BuildingType     = "公寓",
            SizePing         = 19.0,
            Floor            = 2,
            TotalFloors      = 5,
            HasAC            = true,
            HasWasher        = true,
            HasFridge        = false,
            HasWaterHeater   = true,
            HasGas           = false,
            HasInternet      = true,
            HasBed           = true,
            HasParking       = false,
            HasElevator      = false,
            HasBalcony       = true,
        },
        new RentalListing
        {
            LocationCity     = "台中市",
            LocationDistrict = "南屯區",
            Type             = "獨立套房",
            Rent             = 9000,
            Rooms            = 1,
            Bathrooms        = 1,
            IsNearMRT        = false,
            IsNewlyListed    = false,
            AllowsPets       = false,
            ShortTermRent    = false,
            BuildingType     = "電梯大樓",
            SizePing         = 15.9,
            Floor            = 9,
            TotalFloors      = 11,
            HasAC            = true,
            HasWasher        = true,
            HasFridge        = false,
            HasWaterHeater   = true,
            HasGas           = true,
            HasInternet      = true,
            HasBed           = true,
            HasParking       = false,
            HasElevator      = true,
            HasBalcony       = false,
        },
        new RentalListing
        {
            LocationCity     = "台北市",
            LocationDistrict = "內湖區",
            Type             = "整層住家",
            Rent             = 32500,
            Rooms            = 2,
            Bathrooms        = 2,
            IsNearMRT        = true,
            IsNewlyListed    = false,
            AllowsPets       = false,
            ShortTermRent    = false,
            BuildingType     = "公寓",
            SizePing         = 23.0,
            Floor            = 2,
            TotalFloors      = 6,
            HasAC            = true,
            HasWasher        = true,
            HasFridge        = true,
            HasWaterHeater   = true,
            HasGas           = true,
            HasInternet      = true,
            HasBed           = false,
            HasParking       = false,
            HasElevator      = false,
            HasBalcony       = false,
        },
        new RentalListing
        {
            LocationCity     = "台北市",
            LocationDistrict = "大同區",
            Type             = "整層住家",
            Rent             = 21500,
            Rooms            = 3,
            Bathrooms        = 1,
            IsNearMRT        = false,
            IsNewlyListed    = true,
            AllowsPets       = true,
            ShortTermRent    = false,
            BuildingType     = "電梯大樓",
            SizePing         = 38.1,
            Floor            = 4,
            TotalFloors      = 11,
            HasAC            = true,
            HasWasher        = true,
            HasFridge        = false,
            HasWaterHeater   = true,
            HasGas           = true,
            HasInternet      = true,
            HasBed           = false,
            HasParking       = true,
            HasElevator      = true,
            HasBalcony       = true,
        },
        new RentalListing
        {
            LocationCity     = "新北市",
            LocationDistrict = "永和區",
            Type             = "雅房",
            Rent             = 7000,
            Rooms            = 1,
            Bathrooms        = 1,
            IsNearMRT        = false,
            IsNewlyListed    = false,
            AllowsPets       = false,
            ShortTermRent    = false,
            BuildingType     = "公寓",
            SizePing         = 6.4,
            Floor            = 1,
            TotalFloors      = 5,
            HasAC            = true,
            HasWasher        = false,
            HasFridge        = false,
            HasWaterHeater   = true,
            HasGas           = false,
            HasInternet      = true,
            HasBed           = true,
            HasParking       = false,
            HasElevator      = false,
            HasBalcony       = false,
        },
        new RentalListing
        {
            LocationCity     = "高雄市",
            LocationDistrict = "楠梓區",
            Type             = "整層住家",
            Rent             = 21000,
            Rooms            = 3,
            Bathrooms        = 1,
            IsNearMRT        = false,
            IsNewlyListed    = false,
            AllowsPets       = true,
            ShortTermRent    = true,
            BuildingType     = "公寓",
            SizePing         = 46.3,
            Floor            = 1,
            TotalFloors      = 4,
            HasAC            = true,
            HasWasher        = true,
            HasFridge        = true,
            HasWaterHeater   = true,
            HasGas           = true,
            HasInternet      = true,
            HasBed           = false,
            HasParking       = false,
            HasElevator      = false,
            HasBalcony       = false,
        },
        new RentalListing
        {
            LocationCity     = "新北市",
            LocationDistrict = "三重區",
            Type             = "雅房",
            Rent             = 4500,
            Rooms            = 1,
            Bathrooms        = 1,
            IsNearMRT        = true,
            IsNewlyListed    = false,
            AllowsPets       = false,
            ShortTermRent    = true,
            BuildingType     = "電梯大樓",
            SizePing         = 7.7,
            Floor            = 3,
            TotalFloors      = 20,
            HasAC            = true,
            HasWasher        = true,
            HasFridge        = true,
            HasWaterHeater   = true,
            HasGas           = true,
            HasInternet      = true,
            HasBed           = true,
            HasParking       = false,
            HasElevator      = true,
            HasBalcony       = false,
        },
        new RentalListing
        {
            LocationCity     = "桃園市",
            LocationDistrict = "中壢區",
            Type             = "分租套房",
            Rent             = 11500,
            Rooms            = 1,
            Bathrooms        = 1,
            IsNearMRT        = true,
            IsNewlyListed    = false,
            AllowsPets       = false,
            ShortTermRent    = false,
            BuildingType     = "公寓",
            SizePing         = 11.0,
            Floor            = 2,
            TotalFloors      = 4,
            HasAC            = true,
            HasWasher        = true,
            HasFridge        = true,
            HasWaterHeater   = true,
            HasGas           = false,
            HasInternet      = true,
            HasBed           = true,
            HasParking       = false,
            HasElevator      = true,
            HasBalcony       = false,
        },
        new RentalListing
        {
            LocationCity     = "高雄市",
            LocationDistrict = "鼓山區",
            Type             = "獨立套房",
            Rent             = 18500,
            Rooms            = 1,
            Bathrooms        = 1,
            IsNearMRT        = false,
            IsNewlyListed    = false,
            AllowsPets       = false,
            ShortTermRent    = true,
            BuildingType     = "公寓",
            SizePing         = 13.3,
            Floor            = 2,
            TotalFloors      = 4,
            HasAC            = true,
            HasWasher        = true,
            HasFridge        = false,
            HasWaterHeater   = true,
            HasGas           = false,
            HasInternet      = false,
            HasBed           = true,
            HasParking       = false,
            HasElevator      = false,
            HasBalcony       = false,
        },
        new RentalListing
        {
            LocationCity     = "台中市",
            LocationDistrict = "太平區",
            Type             = "獨立套房",
            Rent             = 10500,
            Rooms            = 1,
            Bathrooms        = 1,
            IsNearMRT        = false,
            IsNewlyListed    = false,
            AllowsPets       = false,
            ShortTermRent    = false,
            BuildingType     = "公寓",
            SizePing         = 18.4,
            Floor            = 3,
            TotalFloors      = 4,
            HasAC            = true,
            HasWasher        = true,
            HasFridge        = false,
            HasWaterHeater   = true,
            HasGas           = true,
            HasInternet      = true,
            HasBed           = true,
            HasParking       = false,
            HasElevator      = false,
            HasBalcony       = false,
        },
        new RentalListing
        {
            LocationCity     = "新北市",
            LocationDistrict = "新店區",
            Type             = "整層住家",
            Rent             = 60000,
            Rooms            = 3,
            Bathrooms        = 2,
            IsNearMRT        = false,
            IsNewlyListed    = false,
            AllowsPets       = false,
            ShortTermRent    = false,
            BuildingType     = "公寓",
            SizePing         = 28.7,
            Floor            = 3,
            TotalFloors      = 5,
            HasAC            = false,
            HasWasher        = true,
            HasFridge        = false,
            HasWaterHeater   = true,
            HasGas           = false,
            HasInternet      = true,
            HasBed           = true,
            HasParking       = false,
            HasElevator      = false,
            HasBalcony       = true,
        },
        new RentalListing
        {
            LocationCity     = "台南市",
            LocationDistrict = "北區",
            Type             = "雅房",
            Rent             = 8000,
            Rooms            = 1,
            Bathrooms        = 1,
            IsNearMRT        = false,
            IsNewlyListed    = false,
            AllowsPets       = false,
            ShortTermRent    = false,
            BuildingType     = "公寓",
            SizePing         = 4.3,
            Floor            = 5,
            TotalFloors      = 6,
            HasAC            = true,
            HasWasher        = false,
            HasFridge        = false,
            HasWaterHeater   = true,
            HasGas           = false,
            HasInternet      = true,
            HasBed           = false,
            HasParking       = false,
            HasElevator      = false,
            HasBalcony       = true,
        },
        new RentalListing
        {
            LocationCity     = "高雄市",
            LocationDistrict = "鼓山區",
            Type             = "獨立套房",
            Rent             = 10000,
            Rooms            = 1,
            Bathrooms        = 1,
            IsNearMRT        = false,
            IsNewlyListed    = false,
            AllowsPets       = true,
            ShortTermRent    = false,
            BuildingType     = "電梯大樓",
            SizePing         = 13.0,
            Floor            = 9,
            TotalFloors      = 14,
            HasAC            = true,
            HasWasher        = true,
            HasFridge        = true,
            HasWaterHeater   = true,
            HasGas           = true,
            HasInternet      = true,
            HasBed           = false,
            HasParking       = false,
            HasElevator      = true,
            HasBalcony       = false,
        },
        new RentalListing
        {
            LocationCity     = "桃園市",
            LocationDistrict = "龜山區",
            Type             = "整層住家",
            Rent             = 33000,
            Rooms            = 3,
            Bathrooms        = 2,
            IsNearMRT        = true,
            IsNewlyListed    = false,
            AllowsPets       = false,
            ShortTermRent    = true,
            BuildingType     = "電梯大樓",
            SizePing         = 50.3,
            Floor            = 1,
            TotalFloors      = 8,
            HasAC            = true,
            HasWasher        = true,
            HasFridge        = true,
            HasWaterHeater   = true,
            HasGas           = true,
            HasInternet      = true,
            HasBed           = false,
            HasParking       = true,
            HasElevator      = true,
            HasBalcony       = false,
        },
        new RentalListing
        {
            LocationCity     = "台北市",
            LocationDistrict = "信義區",
            Type             = "獨立套房",
            Rent             = 9500,
            Rooms            = 1,
            Bathrooms        = 1,
            IsNearMRT        = true,
            IsNewlyListed    = false,
            AllowsPets       = false,
            ShortTermRent    = false,
            BuildingType     = "公寓",
            SizePing         = 17.6,
            Floor            = 4,
            TotalFloors      = 4,
            HasAC            = true,
            HasWasher        = false,
            HasFridge        = true,
            HasWaterHeater   = true,
            HasGas           = false,
            HasInternet      = true,
            HasBed           = false,
            HasParking       = false,
            HasElevator      = false,
            HasBalcony       = false,
        },
        new RentalListing
        {
            LocationCity     = "台中市",
            LocationDistrict = "北區",
            Type             = "獨立套房",
            Rent             = 17000,
            Rooms            = 1,
            Bathrooms        = 1,
            IsNearMRT        = false,
            IsNewlyListed    = false,
            AllowsPets       = false,
            ShortTermRent    = false,
            BuildingType     = "電梯大樓",
            SizePing         = 11.3,
            Floor            = 2,
            TotalFloors      = 15,
            HasAC            = true,
            HasWasher        = true,
            HasFridge        = true,
            HasWaterHeater   = true,
            HasGas           = true,
            HasInternet      = true,
            HasBed           = true,
            HasParking       = false,
            HasElevator      = true,
            HasBalcony       = true,
        },
        new RentalListing
        {
            LocationCity     = "台中市",
            LocationDistrict = "南區",
            Type             = "整層住家",
            Rent             = 54500,
            Rooms            = 2,
            Bathrooms        = 2,
            IsNearMRT        = false,
            IsNewlyListed    = false,
            AllowsPets       = false,
            ShortTermRent    = false,
            BuildingType     = "透天厝",
            SizePing         = 37.1,
            Floor            = 4,
            TotalFloors      = 4,
            HasAC            = true,
            HasWasher        = true,
            HasFridge        = true,
            HasWaterHeater   = true,
            HasGas           = false,
            HasInternet      = true,
            HasBed           = false,
            HasParking       = false,
            HasElevator      = false,
            HasBalcony       = false,
        },
        new RentalListing
        {
            LocationCity     = "台南市",
            LocationDistrict = "東區",
            Type             = "雅房",
            Rent             = 8000,
            Rooms            = 1,
            Bathrooms        = 1,
            IsNearMRT        = true,
            IsNewlyListed    = false,
            AllowsPets       = false,
            ShortTermRent    = false,
            BuildingType     = "電梯大樓",
            SizePing         = 7.0,
            Floor            = 8,
            TotalFloors      = 10,
            HasAC            = true,
            HasWasher        = false,
            HasFridge        = true,
            HasWaterHeater   = false,
            HasGas           = true,
            HasInternet      = false,
            HasBed           = true,
            HasParking       = false,
            HasElevator      = true,
            HasBalcony       = true,
        },
        new RentalListing
        {
            LocationCity     = "桃園市",
            LocationDistrict = "八德區",
            Type             = "整層住家",
            Rent             = 59500,
            Rooms            = 2,
            Bathrooms        = 2,
            IsNearMRT        = true,
            IsNewlyListed    = false,
            AllowsPets       = true,
            ShortTermRent    = false,
            BuildingType     = "電梯大樓",
            SizePing         = 21.8,
            Floor            = 3,
            TotalFloors      = 8,
            HasAC            = true,
            HasWasher        = true,
            HasFridge        = true,
            HasWaterHeater   = true,
            HasGas           = false,
            HasInternet      = true,
            HasBed           = false,
            HasParking       = true,
            HasElevator      = true,
            HasBalcony       = true,
        },
        new RentalListing
        {
            LocationCity     = "台南市",
            LocationDistrict = "東區",
            Type             = "分租套房",
            Rent             = 9000,
            Rooms            = 1,
            Bathrooms        = 1,
            IsNearMRT        = true,
            IsNewlyListed    = false,
            AllowsPets       = false,
            ShortTermRent    = false,
            BuildingType     = "公寓",
            SizePing         = 11.1,
            Floor            = 2,
            TotalFloors      = 4,
            HasAC            = true,
            HasWasher        = false,
            HasFridge        = false,
            HasWaterHeater   = true,
            HasGas           = true,
            HasInternet      = true,
            HasBed           = true,
            HasParking       = false,
            HasElevator      = false,
            HasBalcony       = false,
        },
        new RentalListing
        {
            LocationCity     = "台北市",
            LocationDistrict = "信義區",
            Type             = "分租套房",
            Rent             = 9500,
            Rooms            = 1,
            Bathrooms        = 2,
            IsNearMRT        = false,
            IsNewlyListed    = false,
            AllowsPets       = false,
            ShortTermRent    = false,
            BuildingType     = "公寓",
            SizePing         = 13.0,
            Floor            = 2,
            TotalFloors      = 5,
            HasAC            = true,
            HasWasher        = true,
            HasFridge        = true,
            HasWaterHeater   = true,
            HasGas           = true,
            HasInternet      = false,
            HasBed           = true,
            HasParking       = true,
            HasElevator      = false,
            HasBalcony       = true,
        },
        new RentalListing
        {
            LocationCity     = "台中市",
            LocationDistrict = "太平區",
            Type             = "雅房",
            Rent             = 6000,
            Rooms            = 1,
            Bathrooms        = 1,
            IsNearMRT        = false,
            IsNewlyListed    = false,
            AllowsPets       = false,
            ShortTermRent    = false,
            BuildingType     = "電梯大樓",
            SizePing         = 3.2,
            Floor            = 6,
            TotalFloors      = 11,
            HasAC            = true,
            HasWasher        = true,
            HasFridge        = false,
            HasWaterHeater   = true,
            HasGas           = false,
            HasInternet      = true,
            HasBed           = true,
            HasParking       = false,
            HasElevator      = true,
            HasBalcony       = false,
        },
        new RentalListing
        {
            LocationCity     = "台中市",
            LocationDistrict = "中區",
            Type             = "整層住家",
            Rent             = 23500,
            Rooms            = 4,
            Bathrooms        = 2,
            IsNearMRT        = true,
            IsNewlyListed    = false,
            AllowsPets       = false,
            ShortTermRent    = false,
            BuildingType     = "透天厝",
            SizePing         = 33.2,
            Floor            = 5,
            TotalFloors      = 5,
            HasAC            = true,
            HasWasher        = true,
            HasFridge        = true,
            HasWaterHeater   = true,
            HasGas           = true,
            HasInternet      = true,
            HasBed           = true,
            HasParking       = false,
            HasElevator      = false,
            HasBalcony       = false,
        },
        new RentalListing
        {
            LocationCity     = "新北市",
            LocationDistrict = "新店區",
            Type             = "雅房",
            Rent             = 5500,
            Rooms            = 1,
            Bathrooms        = 1,
            IsNearMRT        = true,
            IsNewlyListed    = false,
            AllowsPets       = false,
            ShortTermRent    = true,
            BuildingType     = "公寓",
            SizePing         = 8.1,
            Floor            = 2,
            TotalFloors      = 5,
            HasAC            = true,
            HasWasher        = true,
            HasFridge        = true,
            HasWaterHeater   = true,
            HasGas           = false,
            HasInternet      = true,
            HasBed           = true,
            HasParking       = true,
            HasElevator      = false,
            HasBalcony       = true,
        },
        new RentalListing
        {
            LocationCity     = "桃園市",
            LocationDistrict = "桃園區",
            Type             = "整層住家",
            Rent             = 34000,
            Rooms            = 4,
            Bathrooms        = 1,
            IsNearMRT        = true,
            IsNewlyListed    = false,
            AllowsPets       = true,
            ShortTermRent    = true,
            BuildingType     = "公寓",
            SizePing         = 62.3,
            Floor            = 4,
            TotalFloors      = 5,
            HasAC            = true,
            HasWasher        = true,
            HasFridge        = false,
            HasWaterHeater   = true,
            HasGas           = false,
            HasInternet      = true,
            HasBed           = false,
            HasParking       = true,
            HasElevator      = false,
            HasBalcony       = true,
        },
        new RentalListing
        {
            LocationCity     = "台中市",
            LocationDistrict = "北區",
            Type             = "雅房",
            Rent             = 5500,
            Rooms            = 1,
            Bathrooms        = 1,
            IsNearMRT        = true,
            IsNewlyListed    = true,
            AllowsPets       = true,
            ShortTermRent    = false,
            BuildingType     = "公寓",
            SizePing         = 7.0,
            Floor            = 2,
            TotalFloors      = 6,
            HasAC            = true,
            HasWasher        = true,
            HasFridge        = false,
            HasWaterHeater   = true,
            HasGas           = true,
            HasInternet      = true,
            HasBed           = true,
            HasParking       = false,
            HasElevator      = true,
            HasBalcony       = true,
        },
        new RentalListing
        {
            LocationCity     = "桃園市",
            LocationDistrict = "八德區",
            Type             = "雅房",
            Rent             = 4000,
            Rooms            = 1,
            Bathrooms        = 1,
            IsNearMRT        = true,
            IsNewlyListed    = false,
            AllowsPets       = false,
            ShortTermRent    = false,
            BuildingType     = "公寓",
            SizePing         = 6.8,
            Floor            = 1,
            TotalFloors      = 4,
            HasAC            = true,
            HasWasher        = true,
            HasFridge        = false,
            HasWaterHeater   = true,
            HasGas           = false,
            HasInternet      = true,
            HasBed           = true,
            HasParking       = true,
            HasElevator      = true,
            HasBalcony       = true,
        },
        new RentalListing
        {
            LocationCity     = "桃園市",
            LocationDistrict = "蘆竹區",
            Type             = "整層住家",
            Rent             = 23500,
            Rooms            = 2,
            Bathrooms        = 2,
            IsNearMRT        = false,
            IsNewlyListed    = false,
            AllowsPets       = false,
            ShortTermRent    = false,
            BuildingType     = "公寓",
            SizePing         = 30.3,
            Floor            = 4,
            TotalFloors      = 4,
            HasAC            = true,
            HasWasher        = false,
            HasFridge        = false,
            HasWaterHeater   = true,
            HasGas           = true,
            HasInternet      = true,
            HasBed           = true,
            HasParking       = true,
            HasElevator      = false,
            HasBalcony       = true,
        },
        new RentalListing
        {
            LocationCity     = "高雄市",
            LocationDistrict = "鳳山區",
            Type             = "整層住家",
            Rent             = 47000,
            Rooms            = 3,
            Bathrooms        = 2,
            IsNearMRT        = false,
            IsNewlyListed    = true,
            AllowsPets       = false,
            ShortTermRent    = false,
            BuildingType     = "公寓",
            SizePing         = 24.0,
            Floor            = 5,
            TotalFloors      = 5,
            HasAC            = true,
            HasWasher        = true,
            HasFridge        = true,
            HasWaterHeater   = true,
            HasGas           = true,
            HasInternet      = true,
            HasBed           = true,
            HasParking       = true,
            HasElevator      = false,
            HasBalcony       = false,
        },
        new RentalListing
        {
            LocationCity     = "台中市",
            LocationDistrict = "南屯區",
            Type             = "整層住家",
            Rent             = 58000,
            Rooms            = 3,
            Bathrooms        = 2,
            IsNearMRT        = false,
            IsNewlyListed    = true,
            AllowsPets       = false,
            ShortTermRent    = false,
            BuildingType     = "透天厝",
            SizePing         = 47.4,
            Floor            = 1,
            TotalFloors      = 5,
            HasAC            = true,
            HasWasher        = true,
            HasFridge        = false,
            HasWaterHeater   = true,
            HasGas           = false,
            HasInternet      = true,
            HasBed           = true,
            HasParking       = false,
            HasElevator      = false,
            HasBalcony       = true,
        },
        new RentalListing
        {
            LocationCity     = "台南市",
            LocationDistrict = "南區",
            Type             = "雅房",
            Rent             = 5000,
            Rooms            = 1,
            Bathrooms        = 1,
            IsNearMRT        = true,
            IsNewlyListed    = false,
            AllowsPets       = false,
            ShortTermRent    = true,
            BuildingType     = "電梯大樓",
            SizePing         = 9.5,
            Floor            = 14,
            TotalFloors      = 20,
            HasAC            = true,
            HasWasher        = false,
            HasFridge        = true,
            HasWaterHeater   = true,
            HasGas           = false,
            HasInternet      = true,
            HasBed           = true,
            HasParking       = false,
            HasElevator      = true,
            HasBalcony       = false,
        },
        new RentalListing
        {
            LocationCity     = "台中市",
            LocationDistrict = "中區",
            Type             = "分租套房",
            Rent             = 11000,
            Rooms            = 1,
            Bathrooms        = 2,
            IsNearMRT        = true,
            IsNewlyListed    = false,
            AllowsPets       = false,
            ShortTermRent    = false,
            BuildingType     = "電梯大樓",
            SizePing         = 6.7,
            Floor            = 7,
            TotalFloors      = 11,
            HasAC            = true,
            HasWasher        = true,
            HasFridge        = false,
            HasWaterHeater   = false,
            HasGas           = true,
            HasInternet      = true,
            HasBed           = true,
            HasParking       = false,
            HasElevator      = true,
            HasBalcony       = false,
        },
        new RentalListing
        {
            LocationCity     = "台中市",
            LocationDistrict = "南屯區",
            Type             = "雅房",
            Rent             = 3500,
            Rooms            = 1,
            Bathrooms        = 1,
            IsNearMRT        = true,
            IsNewlyListed    = false,
            AllowsPets       = false,
            ShortTermRent    = false,
            BuildingType     = "公寓",
            SizePing         = 8.1,
            Floor            = 3,
            TotalFloors      = 5,
            HasAC            = true,
            HasWasher        = false,
            HasFridge        = true,
            HasWaterHeater   = true,
            HasGas           = false,
            HasInternet      = true,
            HasBed           = false,
            HasParking       = true,
            HasElevator      = true,
            HasBalcony       = false,
        },
        new RentalListing
        {
            LocationCity     = "桃園市",
            LocationDistrict = "八德區",
            Type             = "整層住家",
            Rent             = 45500,
            Rooms            = 2,
            Bathrooms        = 3,
            IsNearMRT        = false,
            IsNewlyListed    = true,
            AllowsPets       = false,
            ShortTermRent    = false,
            BuildingType     = "電梯大樓",
            SizePing         = 64.0,
            Floor            = 10,
            TotalFloors      = 19,
            HasAC            = true,
            HasWasher        = true,
            HasFridge        = true,
            HasWaterHeater   = true,
            HasGas           = false,
            HasInternet      = true,
            HasBed           = true,
            HasParking       = false,
            HasElevator      = true,
            HasBalcony       = false,
        },
        new RentalListing
        {
            LocationCity     = "新北市",
            LocationDistrict = "樹林區",
            Type             = "獨立套房",
            Rent             = 10500,
            Rooms            = 1,
            Bathrooms        = 1,
            IsNearMRT        = false,
            IsNewlyListed    = false,
            AllowsPets       = false,
            ShortTermRent    = false,
            BuildingType     = "電梯大樓",
            SizePing         = 13.5,
            Floor            = 1,
            TotalFloors      = 18,
            HasAC            = true,
            HasWasher        = false,
            HasFridge        = false,
            HasWaterHeater   = true,
            HasGas           = false,
            HasInternet      = true,
            HasBed           = false,
            HasParking       = false,
            HasElevator      = true,
            HasBalcony       = false,
        },
        new RentalListing
        {
            LocationCity     = "台中市",
            LocationDistrict = "南屯區",
            Type             = "獨立套房",
            Rent             = 13000,
            Rooms            = 1,
            Bathrooms        = 1,
            IsNearMRT        = true,
            IsNewlyListed    = false,
            AllowsPets       = false,
            ShortTermRent    = false,
            BuildingType     = "公寓",
            SizePing         = 14.9,
            Floor            = 4,
            TotalFloors      = 6,
            HasAC            = true,
            HasWasher        = true,
            HasFridge        = true,
            HasWaterHeater   = true,
            HasGas           = true,
            HasInternet      = true,
            HasBed           = false,
            HasParking       = false,
            HasElevator      = false,
            HasBalcony       = false,
        },
        new RentalListing
        {
            LocationCity     = "高雄市",
            LocationDistrict = "前鎮區",
            Type             = "整層住家",
            Rent             = 58000,
            Rooms            = 3,
            Bathrooms        = 3,
            IsNearMRT        = false,
            IsNewlyListed    = true,
            AllowsPets       = false,
            ShortTermRent    = false,
            BuildingType     = "公寓",
            SizePing         = 49.1,
            Floor            = 3,
            TotalFloors      = 6,
            HasAC            = true,
            HasWasher        = true,
            HasFridge        = true,
            HasWaterHeater   = false,
            HasGas           = true,
            HasInternet      = false,
            HasBed           = false,
            HasParking       = true,
            HasElevator      = false,
            HasBalcony       = true,
        },
        new RentalListing
        {
            LocationCity     = "桃園市",
            LocationDistrict = "龜山區",
            Type             = "整層住家",
            Rent             = 47500,
            Rooms            = 3,
            Bathrooms        = 2,
            IsNearMRT        = true,
            IsNewlyListed    = false,
            AllowsPets       = false,
            ShortTermRent    = true,
            BuildingType     = "別墅",
            SizePing         = 63.3,
            Floor            = 3,
            TotalFloors      = 5,
            HasAC            = true,
            HasWasher        = false,
            HasFridge        = true,
            HasWaterHeater   = true,
            HasGas           = false,
            HasInternet      = true,
            HasBed           = false,
            HasParking       = false,
            HasElevator      = false,
            HasBalcony       = false,
        },
        new RentalListing
        {
            LocationCity     = "桃園市",
            LocationDistrict = "八德區",
            Type             = "整層住家",
            Rent             = 58500,
            Rooms            = 3,
            Bathrooms        = 3,
            IsNearMRT        = false,
            IsNewlyListed    = false,
            AllowsPets       = false,
            ShortTermRent    = true,
            BuildingType     = "公寓",
            SizePing         = 57.1,
            Floor            = 1,
            TotalFloors      = 4,
            HasAC            = true,
            HasWasher        = true,
            HasFridge        = true,
            HasWaterHeater   = true,
            HasGas           = false,
            HasInternet      = false,
            HasBed           = false,
            HasParking       = false,
            HasElevator      = false,
            HasBalcony       = true,
        },
        new RentalListing
        {
            LocationCity     = "台北市",
            LocationDistrict = "松山區",
            Type             = "雅房",
            Rent             = 5500,
            Rooms            = 1,
            Bathrooms        = 1,
            IsNearMRT        = false,
            IsNewlyListed    = true,
            AllowsPets       = false,
            ShortTermRent    = false,
            BuildingType     = "電梯大樓",
            SizePing         = 3.2,
            Floor            = 4,
            TotalFloors      = 15,
            HasAC            = false,
            HasWasher        = true,
            HasFridge        = true,
            HasWaterHeater   = true,
            HasGas           = true,
            HasInternet      = false,
            HasBed           = true,
            HasParking       = false,
            HasElevator      = true,
            HasBalcony       = false,
        },
        new RentalListing
        {
            LocationCity     = "台南市",
            LocationDistrict = "東區",
            Type             = "整層住家",
            Rent             = 39000,
            Rooms            = 3,
            Bathrooms        = 2,
            IsNearMRT        = false,
            IsNewlyListed    = false,
            AllowsPets       = true,
            ShortTermRent    = false,
            BuildingType     = "公寓",
            SizePing         = 31.0,
            Floor            = 2,
            TotalFloors      = 6,
            HasAC            = true,
            HasWasher        = true,
            HasFridge        = true,
            HasWaterHeater   = false,
            HasGas           = false,
            HasInternet      = true,
            HasBed           = false,
            HasParking       = true,
            HasElevator      = false,
            HasBalcony       = true,
        },
        new RentalListing
        {
            LocationCity     = "桃園市",
            LocationDistrict = "八德區",
            Type             = "分租套房",
            Rent             = 4500,
            Rooms            = 1,
            Bathrooms        = 1,
            IsNearMRT        = false,
            IsNewlyListed    = false,
            AllowsPets       = false,
            ShortTermRent    = false,
            BuildingType     = "電梯大樓",
            SizePing         = 6.6,
            Floor            = 4,
            TotalFloors      = 16,
            HasAC            = true,
            HasWasher        = true,
            HasFridge        = false,
            HasWaterHeater   = true,
            HasGas           = false,
            HasInternet      = false,
            HasBed           = true,
            HasParking       = false,
            HasElevator      = true,
            HasBalcony       = false,
        },
        new RentalListing
        {
            LocationCity     = "台北市",
            LocationDistrict = "松山區",
            Type             = "雅房",
            Rent             = 6500,
            Rooms            = 1,
            Bathrooms        = 1,
            IsNearMRT        = false,
            IsNewlyListed    = true,
            AllowsPets       = false,
            ShortTermRent    = false,
            BuildingType     = "公寓",
            SizePing         = 7.8,
            Floor            = 3,
            TotalFloors      = 4,
            HasAC            = true,
            HasWasher        = true,
            HasFridge        = false,
            HasWaterHeater   = true,
            HasGas           = true,
            HasInternet      = true,
            HasBed           = true,
            HasParking       = false,
            HasElevator      = false,
            HasBalcony       = false,
        },
        new RentalListing
        {
            LocationCity     = "台南市",
            LocationDistrict = "西區",
            Type             = "雅房",
            Rent             = 7000,
            Rooms            = 1,
            Bathrooms        = 1,
            IsNearMRT        = false,
            IsNewlyListed    = false,
            AllowsPets       = false,
            ShortTermRent    = false,
            BuildingType     = "電梯大樓",
            SizePing         = 9.2,
            Floor            = 7,
            TotalFloors      = 14,
            HasAC            = false,
            HasWasher        = true,
            HasFridge        = true,
            HasWaterHeater   = true,
            HasGas           = true,
            HasInternet      = true,
            HasBed           = true,
            HasParking       = false,
            HasElevator      = true,
            HasBalcony       = true,
        },
        new RentalListing
        {
            LocationCity     = "台北市",
            LocationDistrict = "中正區",
            Type             = "分租套房",
            Rent             = 9500,
            Rooms            = 1,
            Bathrooms        = 2,
            IsNearMRT        = false,
            IsNewlyListed    = false,
            AllowsPets       = false,
            ShortTermRent    = false,
            BuildingType     = "電梯大樓",
            SizePing         = 6.1,
            Floor            = 2,
            TotalFloors      = 19,
            HasAC            = true,
            HasWasher        = true,
            HasFridge        = true,
            HasWaterHeater   = true,
            HasGas           = false,
            HasInternet      = true,
            HasBed           = true,
            HasParking       = false,
            HasElevator      = true,
            HasBalcony       = false,
        },
        new RentalListing
        {
            LocationCity     = "台南市",
            LocationDistrict = "東區",
            Type             = "分租套房",
            Rent             = 4500,
            Rooms            = 1,
            Bathrooms        = 1,
            IsNearMRT        = false,
            IsNewlyListed    = false,
            AllowsPets       = false,
            ShortTermRent    = true,
            BuildingType     = "電梯大樓",
            SizePing         = 6.6,
            Floor            = 3,
            TotalFloors      = 8,
            HasAC            = true,
            HasWasher        = true,
            HasFridge        = false,
            HasWaterHeater   = true,
            HasGas           = true,
            HasInternet      = true,
            HasBed           = true,
            HasParking       = false,
            HasElevator      = true,
            HasBalcony       = false,
        },
        new RentalListing
        {
            LocationCity     = "台南市",
            LocationDistrict = "北區",
            Type             = "整層住家",
            Rent             = 27500,
            Rooms            = 2,
            Bathrooms        = 1,
            IsNearMRT        = false,
            IsNewlyListed    = false,
            AllowsPets       = false,
            ShortTermRent    = false,
            BuildingType     = "透天厝",
            SizePing         = 27.1,
            Floor            = 4,
            TotalFloors      = 4,
            HasAC            = true,
            HasWasher        = true,
            HasFridge        = true,
            HasWaterHeater   = true,
            HasGas           = true,
            HasInternet      = true,
            HasBed           = true,
            HasParking       = false,
            HasElevator      = false,
            HasBalcony       = true,
        },
        new RentalListing
        {
            LocationCity     = "桃園市",
            LocationDistrict = "八德區",
            Type             = "獨立套房",
            Rent             = 19000,
            Rooms            = 1,
            Bathrooms        = 1,
            IsNearMRT        = true,
            IsNewlyListed    = false,
            AllowsPets       = false,
            ShortTermRent    = false,
            BuildingType     = "公寓",
            SizePing         = 11.1,
            Floor            = 4,
            TotalFloors      = 5,
            HasAC            = true,
            HasWasher        = false,
            HasFridge        = true,
            HasWaterHeater   = true,
            HasGas           = true,
            HasInternet      = true,
            HasBed           = false,
            HasParking       = false,
            HasElevator      = false,
            HasBalcony       = false,
        },
        new RentalListing
        {
            LocationCity     = "高雄市",
            LocationDistrict = "鳳山區",
            Type             = "分租套房",
            Rent             = 5000,
            Rooms            = 1,
            Bathrooms        = 1,
            IsNearMRT        = true,
            IsNewlyListed    = false,
            AllowsPets       = true,
            ShortTermRent    = false,
            BuildingType     = "電梯大樓",
            SizePing         = 8.6,
            Floor            = 12,
            TotalFloors      = 19,
            HasAC            = true,
            HasWasher        = true,
            HasFridge        = true,
            HasWaterHeater   = true,
            HasGas           = true,
            HasInternet      = true,
            HasBed           = true,
            HasParking       = false,
            HasElevator      = true,
            HasBalcony       = false,
        },
        new RentalListing
        {
            LocationCity     = "桃園市",
            LocationDistrict = "龜山區",
            Type             = "獨立套房",
            Rent             = 10500,
            Rooms            = 1,
            Bathrooms        = 1,
            IsNearMRT        = false,
            IsNewlyListed    = false,
            AllowsPets       = true,
            ShortTermRent    = false,
            BuildingType     = "公寓",
            SizePing         = 9.2,
            Floor            = 2,
            TotalFloors      = 6,
            HasAC            = true,
            HasWasher        = false,
            HasFridge        = false,
            HasWaterHeater   = true,
            HasGas           = false,
            HasInternet      = true,
            HasBed           = false,
            HasParking       = false,
            HasElevator      = false,
            HasBalcony       = false,
        },
        new RentalListing
        {
            LocationCity     = "新北市",
            LocationDistrict = "樹林區",
            Type             = "整層住家",
            Rent             = 48000,
            Rooms            = 3,
            Bathrooms        = 2,
            IsNearMRT        = true,
            IsNewlyListed    = false,
            AllowsPets       = true,
            ShortTermRent    = false,
            BuildingType     = "公寓",
            SizePing         = 39.9,
            Floor            = 5,
            TotalFloors      = 5,
            HasAC            = true,
            HasWasher        = true,
            HasFridge        = false,
            HasWaterHeater   = true,
            HasGas           = false,
            HasInternet      = true,
            HasBed           = false,
            HasParking       = false,
            HasElevator      = false,
            HasBalcony       = true,
        },
        new RentalListing
        {
            LocationCity     = "台南市",
            LocationDistrict = "西區",
            Type             = "分租套房",
            Rent             = 9000,
            Rooms            = 1,
            Bathrooms        = 1,
            IsNearMRT        = false,
            IsNewlyListed    = true,
            AllowsPets       = false,
            ShortTermRent    = true,
            BuildingType     = "電梯大樓",
            SizePing         = 9.3,
            Floor            = 6,
            TotalFloors      = 9,
            HasAC            = true,
            HasWasher        = false,
            HasFridge        = true,
            HasWaterHeater   = true,
            HasGas           = true,
            HasInternet      = false,
            HasBed           = true,
            HasParking       = false,
            HasElevator      = true,
            HasBalcony       = false,
        },
        new RentalListing
        {
            LocationCity     = "台北市",
            LocationDistrict = "大同區",
            Type             = "分租套房",
            Rent             = 5000,
            Rooms            = 1,
            Bathrooms        = 1,
            IsNearMRT        = true,
            IsNewlyListed    = false,
            AllowsPets       = true,
            ShortTermRent    = false,
            BuildingType     = "電梯大樓",
            SizePing         = 8.0,
            Floor            = 5,
            TotalFloors      = 19,
            HasAC            = false,
            HasWasher        = true,
            HasFridge        = true,
            HasWaterHeater   = true,
            HasGas           = false,
            HasInternet      = true,
            HasBed           = true,
            HasParking       = false,
            HasElevator      = true,
            HasBalcony       = false,
        },
        new RentalListing
        {
            LocationCity     = "高雄市",
            LocationDistrict = "苓雅區",
            Type             = "雅房",
            Rent             = 7500,
            Rooms            = 1,
            Bathrooms        = 1,
            IsNearMRT        = false,
            IsNewlyListed    = false,
            AllowsPets       = true,
            ShortTermRent    = true,
            BuildingType     = "公寓",
            SizePing         = 5.5,
            Floor            = 3,
            TotalFloors      = 4,
            HasAC            = true,
            HasWasher        = false,
            HasFridge        = true,
            HasWaterHeater   = true,
            HasGas           = false,
            HasInternet      = false,
            HasBed           = true,
            HasParking       = false,
            HasElevator      = false,
            HasBalcony       = true,
        },
        new RentalListing
        {
            LocationCity     = "台中市",
            LocationDistrict = "北屯區",
            Type             = "獨立套房",
            Rent             = 9500,
            Rooms            = 1,
            Bathrooms        = 1,
            IsNearMRT        = false,
            IsNewlyListed    = false,
            AllowsPets       = false,
            ShortTermRent    = false,
            BuildingType     = "公寓",
            SizePing         = 18.0,
            Floor            = 3,
            TotalFloors      = 5,
            HasAC            = true,
            HasWasher        = true,
            HasFridge        = true,
            HasWaterHeater   = true,
            HasGas           = false,
            HasInternet      = true,
            HasBed           = false,
            HasParking       = false,
            HasElevator      = false,
            HasBalcony       = false,
        },
        new RentalListing
        {
            LocationCity     = "台中市",
            LocationDistrict = "北區",
            Type             = "雅房",
            Rent             = 7500,
            Rooms            = 1,
            Bathrooms        = 1,
            IsNearMRT        = false,
            IsNewlyListed    = false,
            AllowsPets       = false,
            ShortTermRent    = true,
            BuildingType     = "公寓",
            SizePing         = 6.7,
            Floor            = 1,
            TotalFloors      = 5,
            HasAC            = true,
            HasWasher        = false,
            HasFridge        = true,
            HasWaterHeater   = true,
            HasGas           = true,
            HasInternet      = false,
            HasBed           = true,
            HasParking       = false,
            HasElevator      = false,
            HasBalcony       = true,
        },
        new RentalListing
        {
            LocationCity     = "台中市",
            LocationDistrict = "東區",
            Type             = "整層住家",
            Rent             = 44500,
            Rooms            = 3,
            Bathrooms        = 2,
            IsNearMRT        = true,
            IsNewlyListed    = false,
            AllowsPets       = true,
            ShortTermRent    = false,
            BuildingType     = "別墅",
            SizePing         = 22.4,
            Floor            = 2,
            TotalFloors      = 3,
            HasAC            = true,
            HasWasher        = true,
            HasFridge        = true,
            HasWaterHeater   = true,
            HasGas           = true,
            HasInternet      = false,
            HasBed           = false,
            HasParking       = false,
            HasElevator      = false,
            HasBalcony       = false,
        },
        new RentalListing
        {
            LocationCity     = "台北市",
            LocationDistrict = "北投區",
            Type             = "獨立套房",
            Rent             = 9000,
            Rooms            = 1,
            Bathrooms        = 1,
            IsNearMRT        = true,
            IsNewlyListed    = false,
            AllowsPets       = false,
            ShortTermRent    = false,
            BuildingType     = "電梯大樓",
            SizePing         = 14.6,
            Floor            = 5,
            TotalFloors      = 11,
            HasAC            = true,
            HasWasher        = false,
            HasFridge        = true,
            HasWaterHeater   = true,
            HasGas           = false,
            HasInternet      = true,
            HasBed           = false,
            HasParking       = false,
            HasElevator      = true,
            HasBalcony       = true,
        },
        new RentalListing
        {
            LocationCity     = "桃園市",
            LocationDistrict = "八德區",
            Type             = "雅房",
            Rent             = 4500,
            Rooms            = 1,
            Bathrooms        = 1,
            IsNearMRT        = false,
            IsNewlyListed    = false,
            AllowsPets       = false,
            ShortTermRent    = false,
            BuildingType     = "公寓",
            SizePing         = 7.7,
            Floor            = 5,
            TotalFloors      = 6,
            HasAC            = true,
            HasWasher        = true,
            HasFridge        = false,
            HasWaterHeater   = true,
            HasGas           = true,
            HasInternet      = true,
            HasBed           = true,
            HasParking       = false,
            HasElevator      = false,
            HasBalcony       = false,
        },
        new RentalListing
        {
            LocationCity     = "高雄市",
            LocationDistrict = "楠梓區",
            Type             = "獨立套房",
            Rent             = 7500,
            Rooms            = 1,
            Bathrooms        = 1,
            IsNearMRT        = false,
            IsNewlyListed    = false,
            AllowsPets       = true,
            ShortTermRent    = false,
            BuildingType     = "電梯大樓",
            SizePing         = 12.2,
            Floor            = 16,
            TotalFloors      = 19,
            HasAC            = true,
            HasWasher        = true,
            HasFridge        = true,
            HasWaterHeater   = true,
            HasGas           = true,
            HasInternet      = false,
            HasBed           = false,
            HasParking       = false,
            HasElevator      = true,
            HasBalcony       = false,
        },
        new RentalListing
        {
            LocationCity     = "桃園市",
            LocationDistrict = "中壢區",
            Type             = "獨立套房",
            Rent             = 11500,
            Rooms            = 1,
            Bathrooms        = 1,
            IsNearMRT        = true,
            IsNewlyListed    = false,
            AllowsPets       = false,
            ShortTermRent    = false,
            BuildingType     = "電梯大樓",
            SizePing         = 12.3,
            Floor            = 6,
            TotalFloors      = 9,
            HasAC            = true,
            HasWasher        = true,
            HasFridge        = false,
            HasWaterHeater   = true,
            HasGas           = false,
            HasInternet      = true,
            HasBed           = true,
            HasParking       = false,
            HasElevator      = true,
            HasBalcony       = true,
        },
        new RentalListing
        {
            LocationCity     = "新北市",
            LocationDistrict = "汐止區",
            Type             = "分租套房",
            Rent             = 7000,
            Rooms            = 1,
            Bathrooms        = 2,
            IsNearMRT        = false,
            IsNewlyListed    = false,
            AllowsPets       = false,
            ShortTermRent    = false,
            BuildingType     = "電梯大樓",
            SizePing         = 5.9,
            Floor            = 8,
            TotalFloors      = 12,
            HasAC            = true,
            HasWasher        = false,
            HasFridge        = true,
            HasWaterHeater   = false,
            HasGas           = true,
            HasInternet      = false,
            HasBed           = false,
            HasParking       = true,
            HasElevator      = true,
            HasBalcony       = false,
        },
        new RentalListing
        {
            LocationCity     = "桃園市",
            LocationDistrict = "桃園區",
            Type             = "整層住家",
            Rent             = 27000,
            Rooms            = 4,
            Bathrooms        = 1,
            IsNearMRT        = false,
            IsNewlyListed    = false,
            AllowsPets       = false,
            ShortTermRent    = false,
            BuildingType     = "電梯大樓",
            SizePing         = 58.2,
            Floor            = 4,
            TotalFloors      = 9,
            HasAC            = true,
            HasWasher        = true,
            HasFridge        = false,
            HasWaterHeater   = true,
            HasGas           = false,
            HasInternet      = true,
            HasBed           = false,
            HasParking       = false,
            HasElevator      = true,
            HasBalcony       = false,
        },
        new RentalListing
        {
            LocationCity     = "新北市",
            LocationDistrict = "中和區",
            Type             = "整層住家",
            Rent             = 29500,
            Rooms            = 4,
            Bathrooms        = 1,
            IsNearMRT        = true,
            IsNewlyListed    = false,
            AllowsPets       = false,
            ShortTermRent    = false,
            BuildingType     = "透天厝",
            SizePing         = 42.5,
            Floor            = 4,
            TotalFloors      = 4,
            HasAC            = true,
            HasWasher        = true,
            HasFridge        = true,
            HasWaterHeater   = true,
            HasGas           = false,
            HasInternet      = false,
            HasBed           = false,
            HasParking       = false,
            HasElevator      = false,
            HasBalcony       = false,
        },
        new RentalListing
        {
            LocationCity     = "高雄市",
            LocationDistrict = "苓雅區",
            Type             = "分租套房",
            Rent             = 11500,
            Rooms            = 1,
            Bathrooms        = 2,
            IsNearMRT        = true,
            IsNewlyListed    = false,
            AllowsPets       = false,
            ShortTermRent    = false,
            BuildingType     = "公寓",
            SizePing         = 7.7,
            Floor            = 5,
            TotalFloors      = 5,
            HasAC            = true,
            HasWasher        = true,
            HasFridge        = true,
            HasWaterHeater   = true,
            HasGas           = false,
            HasInternet      = true,
            HasBed           = false,
            HasParking       = true,
            HasElevator      = false,
            HasBalcony       = false,
        },
        new RentalListing
        {
            LocationCity     = "台中市",
            LocationDistrict = "大里區",
            Type             = "雅房",
            Rent             = 6500,
            Rooms            = 1,
            Bathrooms        = 1,
            IsNearMRT        = true,
            IsNewlyListed    = false,
            AllowsPets       = false,
            ShortTermRent    = false,
            BuildingType     = "電梯大樓",
            SizePing         = 8.8,
            Floor            = 3,
            TotalFloors      = 18,
            HasAC            = true,
            HasWasher        = true,
            HasFridge        = true,
            HasWaterHeater   = false,
            HasGas           = true,
            HasInternet      = false,
            HasBed           = true,
            HasParking       = false,
            HasElevator      = true,
            HasBalcony       = true,
        },
        new RentalListing
        {
            LocationCity     = "新北市",
            LocationDistrict = "永和區",
            Type             = "分租套房",
            Rent             = 11500,
            Rooms            = 1,
            Bathrooms        = 2,
            IsNearMRT        = true,
            IsNewlyListed    = false,
            AllowsPets       = false,
            ShortTermRent    = false,
            BuildingType     = "電梯大樓",
            SizePing         = 11.4,
            Floor            = 5,
            TotalFloors      = 9,
            HasAC            = true,
            HasWasher        = true,
            HasFridge        = true,
            HasWaterHeater   = true,
            HasGas           = false,
            HasInternet      = true,
            HasBed           = true,
            HasParking       = false,
            HasElevator      = true,
            HasBalcony       = true,
        },
        new RentalListing
        {
            LocationCity     = "台南市",
            LocationDistrict = "東區",
            Type             = "整層住家",
            Rent             = 23000,
            Rooms            = 3,
            Bathrooms        = 2,
            IsNearMRT        = false,
            IsNewlyListed    = false,
            AllowsPets       = false,
            ShortTermRent    = false,
            BuildingType     = "別墅",
            SizePing         = 22.0,
            Floor            = 1,
            TotalFloors      = 5,
            HasAC            = true,
            HasWasher        = false,
            HasFridge        = false,
            HasWaterHeater   = true,
            HasGas           = true,
            HasInternet      = true,
            HasBed           = false,
            HasParking       = false,
            HasElevator      = false,
            HasBalcony       = false,
        },
        new RentalListing
        {
            LocationCity     = "桃園市",
            LocationDistrict = "龜山區",
            Type             = "分租套房",
            Rent             = 7500,
            Rooms            = 1,
            Bathrooms        = 2,
            IsNearMRT        = false,
            IsNewlyListed    = false,
            AllowsPets       = true,
            ShortTermRent    = true,
            BuildingType     = "公寓",
            SizePing         = 6.2,
            Floor            = 2,
            TotalFloors      = 5,
            HasAC            = true,
            HasWasher        = true,
            HasFridge        = true,
            HasWaterHeater   = true,
            HasGas           = false,
            HasInternet      = true,
            HasBed           = true,
            HasParking       = false,
            HasElevator      = false,
            HasBalcony       = false,
        },
        new RentalListing
        {
            LocationCity     = "台中市",
            LocationDistrict = "大里區",
            Type             = "雅房",
            Rent             = 7000,
            Rooms            = 1,
            Bathrooms        = 1,
            IsNearMRT        = false,
            IsNewlyListed    = false,
            AllowsPets       = false,
            ShortTermRent    = true,
            BuildingType     = "公寓",
            SizePing         = 9.2,
            Floor            = 5,
            TotalFloors      = 5,
            HasAC            = true,
            HasWasher        = true,
            HasFridge        = false,
            HasWaterHeater   = true,
            HasGas           = true,
            HasInternet      = true,
            HasBed           = true,
            HasParking       = false,
            HasElevator      = false,
            HasBalcony       = true,
        },
        new RentalListing
        {
            LocationCity     = "台中市",
            LocationDistrict = "東區",
            Type             = "整層住家",
            Rent             = 43500,
            Rooms            = 3,
            Bathrooms        = 2,
            IsNearMRT        = false,
            IsNewlyListed    = false,
            AllowsPets       = false,
            ShortTermRent    = false,
            BuildingType     = "透天厝",
            SizePing         = 22.3,
            Floor            = 2,
            TotalFloors      = 3,
            HasAC            = true,
            HasWasher        = true,
            HasFridge        = false,
            HasWaterHeater   = true,
            HasGas           = false,
            HasInternet      = true,
            HasBed           = false,
            HasParking       = false,
            HasElevator      = false,
            HasBalcony       = false,
        },
        new RentalListing
        {
            LocationCity     = "台南市",
            LocationDistrict = "東區",
            Type             = "整層住家",
            Rent             = 20000,
            Rooms            = 3,
            Bathrooms        = 3,
            IsNearMRT        = false,
            IsNewlyListed    = true,
            AllowsPets       = false,
            ShortTermRent    = false,
            BuildingType     = "別墅",
            SizePing         = 26.2,
            Floor            = 3,
            TotalFloors      = 3,
            HasAC            = true,
            HasWasher        = true,
            HasFridge        = false,
            HasWaterHeater   = true,
            HasGas           = true,
            HasInternet      = true,
            HasBed           = false,
            HasParking       = false,
            HasElevator      = false,
            HasBalcony       = true,
        },
        new RentalListing
        {
            LocationCity     = "桃園市",
            LocationDistrict = "楊梅區",
            Type             = "雅房",
            Rent             = 8000,
            Rooms            = 1,
            Bathrooms        = 1,
            IsNearMRT        = false,
            IsNewlyListed    = false,
            AllowsPets       = true,
            ShortTermRent    = false,
            BuildingType     = "電梯大樓",
            SizePing         = 5.2,
            Floor            = 8,
            TotalFloors      = 18,
            HasAC            = true,
            HasWasher        = false,
            HasFridge        = true,
            HasWaterHeater   = true,
            HasGas           = true,
            HasInternet      = false,
            HasBed           = true,
            HasParking       = true,
            HasElevator      = true,
            HasBalcony       = true,
        },
        new RentalListing
        {
            LocationCity     = "新北市",
            LocationDistrict = "土城區",
            Type             = "獨立套房",
            Rent             = 13500,
            Rooms            = 1,
            Bathrooms        = 1,
            IsNearMRT        = false,
            IsNewlyListed    = false,
            AllowsPets       = false,
            ShortTermRent    = false,
            BuildingType     = "公寓",
            SizePing         = 14.0,
            Floor            = 2,
            TotalFloors      = 6,
            HasAC            = false,
            HasWasher        = true,
            HasFridge        = true,
            HasWaterHeater   = true,
            HasGas           = false,
            HasInternet      = false,
            HasBed           = false,
            HasParking       = false,
            HasElevator      = false,
            HasBalcony       = true,
        },
        new RentalListing
        {
            LocationCity     = "新北市",
            LocationDistrict = "三重區",
            Type             = "分租套房",
            Rent             = 6000,
            Rooms            = 1,
            Bathrooms        = 1,
            IsNearMRT        = false,
            IsNewlyListed    = false,
            AllowsPets       = false,
            ShortTermRent    = false,
            BuildingType     = "公寓",
            SizePing         = 13.5,
            Floor            = 6,
            TotalFloors      = 6,
            HasAC            = true,
            HasWasher        = true,
            HasFridge        = true,
            HasWaterHeater   = true,
            HasGas           = false,
            HasInternet      = true,
            HasBed           = true,
            HasParking       = false,
            HasElevator      = false,
            HasBalcony       = true,
        },
        new RentalListing
        {
            LocationCity     = "高雄市",
            LocationDistrict = "苓雅區",
            Type             = "分租套房",
            Rent             = 11500,
            Rooms            = 1,
            Bathrooms        = 2,
            IsNearMRT        = false,
            IsNewlyListed    = false,
            AllowsPets       = false,
            ShortTermRent    = false,
            BuildingType     = "電梯大樓",
            SizePing         = 9.0,
            Floor            = 4,
            TotalFloors      = 11,
            HasAC            = true,
            HasWasher        = false,
            HasFridge        = true,
            HasWaterHeater   = true,
            HasGas           = false,
            HasInternet      = true,
            HasBed           = true,
            HasParking       = false,
            HasElevator      = true,
            HasBalcony       = true,
        },
        new RentalListing
        {
            LocationCity     = "台中市",
            LocationDistrict = "南屯區",
            Type             = "獨立套房",
            Rent             = 7000,
            Rooms            = 1,
            Bathrooms        = 1,
            IsNearMRT        = true,
            IsNewlyListed    = false,
            AllowsPets       = false,
            ShortTermRent    = false,
            BuildingType     = "電梯大樓",
            SizePing         = 19.6,
            Floor            = 11,
            TotalFloors      = 15,
            HasAC            = false,
            HasWasher        = true,
            HasFridge        = true,
            HasWaterHeater   = true,
            HasGas           = false,
            HasInternet      = false,
            HasBed           = false,
            HasParking       = false,
            HasElevator      = true,
            HasBalcony       = false,
        },
        new RentalListing
        {
            LocationCity     = "新北市",
            LocationDistrict = "板橋區",
            Type             = "雅房",
            Rent             = 7000,
            Rooms            = 1,
            Bathrooms        = 1,
            IsNearMRT        = false,
            IsNewlyListed    = false,
            AllowsPets       = false,
            ShortTermRent    = false,
            BuildingType     = "公寓",
            SizePing         = 4.3,
            Floor            = 5,
            TotalFloors      = 5,
            HasAC            = true,
            HasWasher        = true,
            HasFridge        = false,
            HasWaterHeater   = true,
            HasGas           = true,
            HasInternet      = true,
            HasBed           = true,
            HasParking       = false,
            HasElevator      = false,
            HasBalcony       = false,
        },
        new RentalListing
        {
            LocationCity     = "高雄市",
            LocationDistrict = "前鎮區",
            Type             = "整層住家",
            Rent             = 39500,
            Rooms            = 3,
            Bathrooms        = 2,
            IsNearMRT        = true,
            IsNewlyListed    = false,
            AllowsPets       = true,
            ShortTermRent    = true,
            BuildingType     = "別墅",
            SizePing         = 55.6,
            Floor            = 3,
            TotalFloors      = 4,
            HasAC            = true,
            HasWasher        = true,
            HasFridge        = true,
            HasWaterHeater   = true,
            HasGas           = false,
            HasInternet      = false,
            HasBed           = true,
            HasParking       = false,
            HasElevator      = true,
            HasBalcony       = false,
        },
        new RentalListing
        {
            LocationCity     = "高雄市",
            LocationDistrict = "左營區",
            Type             = "整層住家",
            Rent             = 60500,
            Rooms            = 3,
            Bathrooms        = 2,
            IsNearMRT        = false,
            IsNewlyListed    = false,
            AllowsPets       = false,
            ShortTermRent    = false,
            BuildingType     = "別墅",
            SizePing         = 25.3,
            Floor            = 5,
            TotalFloors      = 5,
            HasAC            = true,
            HasWasher        = false,
            HasFridge        = true,
            HasWaterHeater   = true,
            HasGas           = false,
            HasInternet      = true,
            HasBed           = false,
            HasParking       = false,
            HasElevator      = false,
            HasBalcony       = false,
        },
        new RentalListing
        {
            LocationCity     = "台中市",
            LocationDistrict = "大里區",
            Type             = "獨立套房",
            Rent             = 19000,
            Rooms            = 1,
            Bathrooms        = 1,
            IsNearMRT        = true,
            IsNewlyListed    = false,
            AllowsPets       = false,
            ShortTermRent    = false,
            BuildingType     = "電梯大樓",
            SizePing         = 11.0,
            Floor            = 2,
            TotalFloors      = 9,
            HasAC            = true,
            HasWasher        = true,
            HasFridge        = true,
            HasWaterHeater   = true,
            HasGas           = true,
            HasInternet      = true,
            HasBed           = true,
            HasParking       = false,
            HasElevator      = true,
            HasBalcony       = false,
        },
        new RentalListing
        {
            LocationCity     = "台中市",
            LocationDistrict = "北屯區",
            Type             = "雅房",
            Rent             = 7000,
            Rooms            = 1,
            Bathrooms        = 1,
            IsNearMRT        = false,
            IsNewlyListed    = false,
            AllowsPets       = false,
            ShortTermRent    = true,
            BuildingType     = "公寓",
            SizePing         = 6.9,
            Floor            = 3,
            TotalFloors      = 5,
            HasAC            = true,
            HasWasher        = true,
            HasFridge        = false,
            HasWaterHeater   = true,
            HasGas           = true,
            HasInternet      = false,
            HasBed           = true,
            HasParking       = false,
            HasElevator      = false,
            HasBalcony       = false,
        },
        new RentalListing
        {
            LocationCity     = "高雄市",
            LocationDistrict = "鳳山區",
            Type             = "分租套房",
            Rent             = 11500,
            Rooms            = 1,
            Bathrooms        = 1,
            IsNearMRT        = false,
            IsNewlyListed    = true,
            AllowsPets       = false,
            ShortTermRent    = true,
            BuildingType     = "公寓",
            SizePing         = 8.4,
            Floor            = 6,
            TotalFloors      = 6,
            HasAC            = false,
            HasWasher        = true,
            HasFridge        = true,
            HasWaterHeater   = false,
            HasGas           = false,
            HasInternet      = true,
            HasBed           = false,
            HasParking       = false,
            HasElevator      = false,
            HasBalcony       = true,
        },
        new RentalListing
        {
            LocationCity     = "台中市",
            LocationDistrict = "西區",
            Type             = "獨立套房",
            Rent             = 14000,
            Rooms            = 1,
            Bathrooms        = 1,
            IsNearMRT        = false,
            IsNewlyListed    = false,
            AllowsPets       = false,
            ShortTermRent    = false,
            BuildingType     = "公寓",
            SizePing         = 12.2,
            Floor            = 4,
            TotalFloors      = 4,
            HasAC            = true,
            HasWasher        = true,
            HasFridge        = true,
            HasWaterHeater   = true,
            HasGas           = false,
            HasInternet      = true,
            HasBed           = true,
            HasParking       = false,
            HasElevator      = false,
            HasBalcony       = false,
        },
        new RentalListing
        {
            LocationCity     = "台北市",
            LocationDistrict = "士林區",
            Type             = "分租套房",
            Rent             = 6000,
            Rooms            = 1,
            Bathrooms        = 2,
            IsNearMRT        = false,
            IsNewlyListed    = false,
            AllowsPets       = false,
            ShortTermRent    = false,
            BuildingType     = "電梯大樓",
            SizePing         = 12.3,
            Floor            = 5,
            TotalFloors      = 11,
            HasAC            = true,
            HasWasher        = true,
            HasFridge        = true,
            HasWaterHeater   = true,
            HasGas           = true,
            HasInternet      = true,
            HasBed           = true,
            HasParking       = true,
            HasElevator      = true,
            HasBalcony       = true,
        },
        new RentalListing
        {
            LocationCity     = "高雄市",
            LocationDistrict = "鳳山區",
            Type             = "分租套房",
            Rent             = 10000,
            Rooms            = 1,
            Bathrooms        = 1,
            IsNearMRT        = false,
            IsNewlyListed    = false,
            AllowsPets       = false,
            ShortTermRent    = false,
            BuildingType     = "電梯大樓",
            SizePing         = 8.7,
            Floor            = 9,
            TotalFloors      = 10,
            HasAC            = true,
            HasWasher        = false,
            HasFridge        = true,
            HasWaterHeater   = false,
            HasGas           = false,
            HasInternet      = true,
            HasBed           = true,
            HasParking       = false,
            HasElevator      = true,
            HasBalcony       = false,
        },
        new RentalListing
        {
            LocationCity     = "台中市",
            LocationDistrict = "東區",
            Type             = "整層住家",
            Rent             = 52000,
            Rooms            = 3,
            Bathrooms        = 1,
            IsNearMRT        = false,
            IsNewlyListed    = true,
            AllowsPets       = false,
            ShortTermRent    = false,
            BuildingType     = "透天厝",
            SizePing         = 52.6,
            Floor            = 1,
            TotalFloors      = 4,
            HasAC            = true,
            HasWasher        = true,
            HasFridge        = false,
            HasWaterHeater   = true,
            HasGas           = false,
            HasInternet      = true,
            HasBed           = false,
            HasParking       = false,
            HasElevator      = false,
            HasBalcony       = false,
        },
        new RentalListing
        {
            LocationCity     = "台中市",
            LocationDistrict = "西區",
            Type             = "獨立套房",
            Rent             = 13000,
            Rooms            = 1,
            Bathrooms        = 1,
            IsNearMRT        = false,
            IsNewlyListed    = false,
            AllowsPets       = false,
            ShortTermRent    = false,
            BuildingType     = "電梯大樓",
            SizePing         = 19.0,
            Floor            = 9,
            TotalFloors      = 15,
            HasAC            = true,
            HasWasher        = false,
            HasFridge        = false,
            HasWaterHeater   = true,
            HasGas           = true,
            HasInternet      = true,
            HasBed           = true,
            HasParking       = true,
            HasElevator      = true,
            HasBalcony       = false,
        },
        new RentalListing
        {
            LocationCity     = "高雄市",
            LocationDistrict = "前鎮區",
            Type             = "整層住家",
            Rent             = 34500,
            Rooms            = 4,
            Bathrooms        = 2,
            IsNearMRT        = true,
            IsNewlyListed    = false,
            AllowsPets       = true,
            ShortTermRent    = false,
            BuildingType     = "電梯大樓",
            SizePing         = 44.9,
            Floor            = 6,
            TotalFloors      = 11,
            HasAC            = false,
            HasWasher        = true,
            HasFridge        = false,
            HasWaterHeater   = true,
            HasGas           = false,
            HasInternet      = true,
            HasBed           = false,
            HasParking       = false,
            HasElevator      = true,
            HasBalcony       = true,
        },
        new RentalListing
        {
            LocationCity     = "新北市",
            LocationDistrict = "汐止區",
            Type             = "雅房",
            Rent             = 4500,
            Rooms            = 1,
            Bathrooms        = 1,
            IsNearMRT        = false,
            IsNewlyListed    = false,
            AllowsPets       = false,
            ShortTermRent    = false,
            BuildingType     = "公寓",
            SizePing         = 9.4,
            Floor            = 1,
            TotalFloors      = 6,
            HasAC            = true,
            HasWasher        = true,
            HasFridge        = true,
            HasWaterHeater   = true,
            HasGas           = false,
            HasInternet      = true,
            HasBed           = true,
            HasParking       = false,
            HasElevator      = false,
            HasBalcony       = true,
        },
        new RentalListing
        {
            LocationCity     = "台南市",
            LocationDistrict = "仁德區",
            Type             = "整層住家",
            Rent             = 19000,
            Rooms            = 3,
            Bathrooms        = 2,
            IsNearMRT        = false,
            IsNewlyListed    = false,
            AllowsPets       = false,
            ShortTermRent    = true,
            BuildingType     = "公寓",
            SizePing         = 43.8,
            Floor            = 6,
            TotalFloors      = 6,
            HasAC            = true,
            HasWasher        = true,
            HasFridge        = true,
            HasWaterHeater   = true,
            HasGas           = false,
            HasInternet      = true,
            HasBed           = true,
            HasParking       = false,
            HasElevator      = false,
            HasBalcony       = false,
        },
        new RentalListing
        {
            LocationCity     = "高雄市",
            LocationDistrict = "左營區",
            Type             = "分租套房",
            Rent             = 9500,
            Rooms            = 1,
            Bathrooms        = 2,
            IsNearMRT        = true,
            IsNewlyListed    = false,
            AllowsPets       = true,
            ShortTermRent    = true,
            BuildingType     = "公寓",
            SizePing         = 12.5,
            Floor            = 4,
            TotalFloors      = 4,
            HasAC            = true,
            HasWasher        = true,
            HasFridge        = true,
            HasWaterHeater   = true,
            HasGas           = false,
            HasInternet      = false,
            HasBed           = true,
            HasParking       = false,
            HasElevator      = true,
            HasBalcony       = true,
        },
        new RentalListing
        {
            LocationCity     = "高雄市",
            LocationDistrict = "小港區",
            Type             = "分租套房",
            Rent             = 4500,
            Rooms            = 1,
            Bathrooms        = 2,
            IsNearMRT        = true,
            IsNewlyListed    = false,
            AllowsPets       = true,
            ShortTermRent    = false,
            BuildingType     = "公寓",
            SizePing         = 13.3,
            Floor            = 3,
            TotalFloors      = 4,
            HasAC            = true,
            HasWasher        = false,
            HasFridge        = true,
            HasWaterHeater   = true,
            HasGas           = false,
            HasInternet      = false,
            HasBed           = true,
            HasParking       = false,
            HasElevator      = false,
            HasBalcony       = false,
        },
        new RentalListing
        {
            LocationCity     = "高雄市",
            LocationDistrict = "苓雅區",
            Type             = "分租套房",
            Rent             = 4500,
            Rooms            = 1,
            Bathrooms        = 1,
            IsNearMRT        = false,
            IsNewlyListed    = false,
            AllowsPets       = false,
            ShortTermRent    = false,
            BuildingType     = "電梯大樓",
            SizePing         = 5.9,
            Floor            = 13,
            TotalFloors      = 17,
            HasAC            = true,
            HasWasher        = true,
            HasFridge        = true,
            HasWaterHeater   = true,
            HasGas           = true,
            HasInternet      = true,
            HasBed           = true,
            HasParking       = false,
            HasElevator      = true,
            HasBalcony       = true,
        },
        new RentalListing
        {
            LocationCity     = "新北市",
            LocationDistrict = "中和區",
            Type             = "整層住家",
            Rent             = 35000,
            Rooms            = 3,
            Bathrooms        = 3,
            IsNearMRT        = true,
            IsNewlyListed    = false,
            AllowsPets       = false,
            ShortTermRent    = false,
            BuildingType     = "透天厝",
            SizePing         = 26.9,
            Floor            = 1,
            TotalFloors      = 4,
            HasAC            = true,
            HasWasher        = true,
            HasFridge        = true,
            HasWaterHeater   = true,
            HasGas           = true,
            HasInternet      = true,
            HasBed           = true,
            HasParking       = false,
            HasElevator      = false,
            HasBalcony       = false,
        }
    };
    }
}
